otp.host=http://localhost:8081/
otp.generate.path=/otp/v3/generate
otp.resend.path=/otp/v3/resend
otp.verify.path=/otp/v3/verify
otp.invalidate.path=/otp/v3/invalidate
otp.email.purpose=login
otp.sms.purpose=login
otp.registration.purpose=registration

keycloak.sms.destination.attribute=mobileNumber
keycloak.email.destination.attribute=email