#!/usr/bin/env bash
# Regenerates every file under data/ from pinned inputs and records their hashes in data/TABLES.sha256.
#
# Required environment:
#   JAVA8_HOME  a Java 8 JDK; the reference tables were generated on Corretto 8u504 (java.version 1.8.0_504)
#   RV_JAR      request-validation-1.0.1-SNAPSHOT.jar (verified by sha256 below)
# Optional environment:
#   M2_REPO            Maven local repository (default: $HOME/.m2/repository)
#   JSOUP_JAR          jsoup 1.17.2 jar           (default: the Maven repository layout under M2_REPO)
#   JSOUP_SOURCES_JAR  jsoup 1.17.2 sources jar   (default: the Maven repository layout under M2_REPO)
#   EXPECTED_JAVA_VERSION  default 1.8.0_504
set -euo pipefail

RV_JAR_SHA256="c3b55d47f25d4b027d0109c25dd61b30dda78339a3cb627613ce07004c7e85b4"
JSOUP_JAR_SHA1="1e75b08d7019546a954f1e359477f916f537a34d"
JSOUP_SOURCES_JAR_SHA1="40c83bbe7e07d1593facfac04b78775fa9368d24"
HANDLER_RESOURCE="org/egov/requestvalidation/event-handler-names.txt"

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(dirname "$here")"
data="$root/data"

: "${JAVA8_HOME:?set JAVA8_HOME to a Java 8 JDK}"
: "${RV_JAR:?set RV_JAR to request-validation-1.0.1-SNAPSHOT.jar}"
m2="${M2_REPO:-$HOME/.m2/repository}"
JSOUP_JAR="${JSOUP_JAR:-$m2/org/jsoup/jsoup/1.17.2/jsoup-1.17.2.jar}"
JSOUP_SOURCES_JAR="${JSOUP_SOURCES_JAR:-$m2/org/jsoup/jsoup/1.17.2/jsoup-1.17.2-sources.jar}"
expected_java="${EXPECTED_JAVA_VERSION:-1.8.0_504}"

fail() { echo "generate.sh: $*" >&2; exit 1; }

for f in "$RV_JAR" "$JSOUP_JAR" "$JSOUP_SOURCES_JAR"; do
    [[ -f "$f" ]] || fail "missing input: $f"
done
for tool in unzip sha256sum sha1sum; do
    command -v "$tool" >/dev/null || fail "missing tool: $tool"
done

actual="$(sha256sum "$RV_JAR" | cut -d' ' -f1)"
[[ "$actual" == "$RV_JAR_SHA256" ]] || fail "RV_JAR sha256 $actual, expected $RV_JAR_SHA256"

check_sha1() { # file pinned-sha1
    local file="$1" pinned="$2" actual recorded
    actual="$(sha1sum "$file" | cut -d' ' -f1)"
    [[ "$actual" == "$pinned" ]] || fail "$(basename "$file") sha1 $actual, expected $pinned"
    if [[ -f "$file.sha1" ]]; then
        recorded="$(tr -d ' \r\n' < "$file.sha1" | cut -c1-40)"
        [[ "$recorded" == "$actual" ]] || fail "$(basename "$file") sha1 differs from $(basename "$file").sha1"
    else
        fail "missing $(basename "$file").sha1 next to the jar"
    fi
}
check_sha1 "$JSOUP_JAR" "$JSOUP_JAR_SHA1"
check_sha1 "$JSOUP_SOURCES_JAR" "$JSOUP_SOURCES_JAR_SHA1"

java_version="$("$JAVA8_HOME/bin/java" -XshowSettings:properties -version 2>&1 | sed -n 's/^ *java\.version = //p')"
[[ "$java_version" == "$expected_java" ]] || fail "java.version $java_version, expected $expected_java"

work="$here/.work"
rm -rf "$work"
mkdir -p "$work/classes" "$data"
trap 'rm -rf "$work"' EXIT

unzip -p "$RV_JAR" "$HANDLER_RESOURCE" > "$data/event-handler-names.txt"

"$JAVA8_HOME/bin/javac" -source 8 -target 8 -encoding UTF-8 -nowarn \
    -cp "$JSOUP_JAR" -d "$work/classes" "$here/GenerateTables.java"
"$JAVA8_HOME/bin/java" -cp "$work/classes:$JSOUP_JAR:$RV_JAR" GenerateTables "$data"

{
    echo "# Generated by tools/generate.sh. Inputs:"
    echo "#   sha256 $RV_JAR_SHA256  request-validation-1.0.1-SNAPSHOT.jar"
    echo "#   sha1   $JSOUP_JAR_SHA1  jsoup-1.17.2.jar"
    echo "#   sha1   $JSOUP_SOURCES_JAR_SHA1  jsoup-1.17.2-sources.jar"
    echo "#   java.version $java_version"
    echo "# Outputs (check with: grep -v '^#' data/TABLES.sha256 | sha256sum -c):"
    (cd "$root" && sha256sum data/event-handler-names.txt data/java8-chars.json data/jsoup-entities.json)
} > "$data/TABLES.sha256"

cat "$data/TABLES.sha256"
