package org.egov.payment.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.*;
import org.egov.payment.constants.TransactionAdditionalFields;
import org.egov.tracer.model.AuditDetails;

import java.util.List;
import java.util.Map;

/**
 * Transaction object representing a payment transaction.
 * Field names are kept identical to pg-service — DB column names depend on them.
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class Transaction {

    @JsonProperty(value = "tenantId", access = JsonProperty.Access.READ_ONLY)
    private String tenantId;

    /** Transaction Amount, preferably rounded off to two decimal places */
    @JsonProperty("txnAmount")
    @NotNull
    @Size(min = 1)
    private String txnAmount;

    /** Unique bill ID associated with the transaction */
    @JsonProperty("billId")
    @NotNull
    @Size(min = 1)
    private String billId;

    /** Backward compatibility */
    @JsonProperty("module")
    @Size(min = 1)
    private String module;

    @JsonProperty("consumerCode")
    @NotNull
    @Size(min = 1, max = 128)
    private String consumerCode;

    @JsonProperty("taxAndPayments")
    @NotNull
    @Size(min = 1)
    private List<TaxAndPayment> taxAndPayments;

    /** Brief description for which the payment is being made */
    @JsonProperty("productInfo")
    @NotNull
    @Size(min = 1, max = 512)
    private String productInfo;

    /** Gateway to be used to perform this transaction */
    @JsonProperty("gateway")
    @NotNull
    @Size(min = 2)
    private String gateway;

    @JsonProperty("callbackUrl")
    @NotNull
    @Size(min = 2)
    private String callbackUrl;

    /** Generated by the app after transaction is initiated */
    @JsonProperty("txnId")
    private String txnId;

    @JsonProperty("user")
    @NotNull
    @Valid
    private User user;

    @JsonProperty("redirectUrl")
    private String redirectUrl;

    @JsonProperty("txnStatus")
    private TxnStatusEnum txnStatus;

    @JsonProperty("txnStatusMsg")
    private String txnStatusMsg;

    @JsonProperty("gatewayTxnId")
    private String gatewayTxnId;

    @JsonProperty("gatewayPaymentMode")
    private String gatewayPaymentMode;

    @JsonProperty("gatewayStatusCode")
    private String gatewayStatusCode;

    @JsonProperty("gatewayStatusMsg")
    private String gatewayStatusMsg;

    @JsonProperty("receipt")
    private String receipt;

    @JsonProperty("auditDetails")
    private AuditDetails auditDetails;

    @JsonProperty("additionalDetails")
    private Object additionalDetails;

    /** Entire RAW payment gateway response — not serialized to JSON */
    @JsonIgnore
    private Object responseJson;

    @JsonIgnore
    private Map<TransactionAdditionalFields, Object> additionalFields;

    public enum TxnStatusEnum {
        SUCCESS("SUCCESS"),
        FAILURE("FAILURE"),
        PENDING("PENDING");

        private final String value;

        TxnStatusEnum(String value) {
            this.value = value;
        }

        @JsonCreator
        public static TxnStatusEnum fromValue(String text) {
            for (TxnStatusEnum b : TxnStatusEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        @Override
        @JsonValue
        public String toString() {
            return String.valueOf(value);
        }
    }
}
